  python:
    container_name: python
    build:
      context: .
      dockerfile: python.dockerfile
    volumes:
      - ./pod:/var/www/python/pod
      - ./src:/var/www/python/src
    healthcheck:
      start_period: 10s
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 10s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
    restart: unless-stopped
    networks:
      - arnelify-network
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    tty: true